name: Deploy docs to GitHub Pages

on:
  # Trigger the workflow every time you push or open pull_request to the `master` branch
  # Using a different branch name? Replace `master` with your branch’s name
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      - name: Install dependencies
        shell: bash
        working-directory: ./docs
        run: npm install
      - name: Build documentation
        shell: bash
        working-directory: ./docs
        run: npm run build
      - name: Upload Pages artifact
        if: github.event_name != 'pull_request'
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./docs/dist/"
  deploy:
    needs: build
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4